name: pyglider
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - matplotlib
  - numpy
  - pip
  - xarray
  - dask
  - netcdf4
  - pyyaml
  - seawater
  - gsw
  - scipy
  - jinja2
  - geojson
  - simplekml
  - webcolors
  - bitstring
  - pytest
